- id: 1
  name: Cement feeding system
  image: Cement Feeding.jpg
  email: email@gmail.com
  phone: 9659 43 21

- id: 2
  name: Roots Blower
  image: Roots Blower1.jpg
  email: email@gmail.com
  phone: 9659 43 21

- id: 3
  name: Vacuum Pump
  image: Vacuum Pump.jpg
  email: email@gmail.com
  phone: 9659 43 21
